In [111]:
import pyvista as pv
import numpy as np
from pyvista import examples

pv.set_plot_theme("document")

# Create a new camera
camera = pv.Camera()
near_range = 0.3
far_range = 0.8
camera.clipping_range = (near_range, far_range)

# Set the position of the drawn camera
camera.position = (1, 0, 0)  # Change this to the desired position
camera.focal_point = (0, 0, 0)  # The point the camera is looking at

# Calculate direction
unit_vector = np.array(camera.direction) / np.linalg.norm(
    np.array([camera.focal_point]) - np.array([camera.position])
)

# Create frustum for the drawn camera
frustum = camera.view_frustum(1.0)

position = camera.position
focal_point = camera.focal_point
line = pv.Line(position, focal_point)

# Load and position the bunny mesh
bunny = examples.download_bunny()
xyz = camera.position + unit_vector * 0.6 - np.mean(bunny.points, axis=0)
bunny.translate(xyz, inplace=True)

# Initialize the plotter
pl = pv.Plotter()
pl.add_text("3D projection")
pl.add_mesh(bunny)
pl.add_mesh(frustum, style="wireframe")  # Draw the frustum of the camera
pl.add_mesh(line, color="b")            # Draw a line from the camera to the focal point
pl.add_point_labels(
    [
        position,
        camera.position + unit_vector * near_range,
        camera.position + unit_vector * far_range,
        focal_point,
    ],
    ["Camera Position", "Near Clipping Plane", "Far Clipping Plane", "Focal Point"],
    margin=0,
    fill_shape=False,
    font_size=14,
    shape_color="white",
    point_color="red",
    text_color="black",
)

# Change the viewing camera (the camera you use to view the scene)
pl.camera.position = (1, 1, 1)
pl.camera.focal_point = (0, 0, 0)
pl.camera.up = (0.0, 0.0, 1.0)
pl.camera.zoom(0.5)

# Show the axes for reference
pl.show_axes()

# Show the plot



In [116]:
# Camera intrinsics
f_x, f_y = 0.3, 0.3  # Focal lengths
img_height = 300
img_width = 300

# Create plane of the image
camera_center=np.array([1,0,0])
focal_point=np.array([0,0,0])
v=focal_point-camera_center # dir vector
v_norm=v/np.linalg.norm(v)
distance=near_range
Pc = camera_center + distance*v_norm
print("yppyp")
print(Pc)


# Some random vector to start with cross product (is not used in final)
if v_norm[0] == 0 and v_norm[1] == 0:  # If v is along the Z-axis
    w = np.array([1, 0, 0])
else:
    w = np.array([0, 0, 1])

# Step 2: Compute the first orthogonal vector
u1 = np.cross(v_norm, w)
u1 = u1 / np.linalg.norm(u1)  # Normalize

# Step 3: Compute the second orthogonal vector
u2 = np.cross(v_norm, u1)
u2 = u2 / np.linalg.norm(u2)  # Normalize

# Generate points on the plane
# Parametrize the plane using the two basis vectors
n_points = 20  # Number of points along each axis for visualization
alphas = np.linspace(-0.1, 0.1, n_points)  # Parameter for u1
betas = np.linspace(-0.1, 0.1, n_points)   # Parameter for u2

plane_points = [
    Pc + alpha * u1 + beta * u2
    for alpha in alphas
    for beta in betas
]

np_plane_points=np.array(plane_points)
camera_center_repeated = np.tile(camera_center, (np_plane_points.shape[0], 1))
vectors_to_plane = np_plane_points - camera_center_repeated
vector_magnitudes = np.linalg.norm(vectors_to_plane, axis=1, keepdims=True)  # Compute magnitudes
normalized_vectors = vectors_to_plane / vector_magnitudes
desired_length = 5 
scaled_vectors = normalized_vectors * desired_length
points_at_distance = camera_center + scaled_vectors
print(points_at_distance)
# create

plane_points = np.array(plane_points)

# Visualize the plane

pl.add_points(plane_points, color="blue", render_points_as_spheres=True, point_size=5)
pl.add_points(points_at_distance, color="blue", render_points_as_spheres=True, point_size=5)
#plotter.add_arrows(P0, v_norm, mag=distance, color="red", label="Direction Vector")
#plotter.add_mesh(pv.Sphere(radius=0.1, center=P0), color="green", label="Starting Point")
#pl.add_mesh(pv.Sphere(radius=0.1, center=Pc), color="yellow", label="Point on Plane")




pl.add_arrows(np.array([1,0,0]),np.array([-1,0,0]), mag=0.2)
#pl.add_mesh(point_cloud, color='red', point_size=5, render_points_as_spheres=True, label="3D Point")
pl.add_axes()  # Add 3D axes to the plot
#pl.show_grid()  # Show a grid for reference
pl.show()

yppyp
[0.7 0.  0. ]
[[-3.52267017 -1.50755672  1.50755672]
 [-3.56423758 -1.52141253  1.36126384]
 [-3.6021649  -1.53405497  1.21109603]
 ...
 [-3.6021649   1.53405497 -1.21109603]
 [-3.56423758  1.52141253 -1.36126384]
 [-3.52267017  1.50755672 -1.50755672]]
A view with name (P_0x7c0d9aae7af0_53) is already registered
 => returning previous one


Widget(value='<iframe src="http://localhost:34075/index.html?ui=P_0x7c0d9aae7af0_53&reconnect=auto" class="pyv…